openapi: 3.0.3
info:
  description: API access to your community.
  title: Vanilla Addons Roles API
  version: '2.0'
servers:
- url: https://open.vanillaforums.com/api/v2
tags:
- name: Roles
paths:
  /roles:
    get:
      parameters:
      - description: 'Include roles in which membbership is personal information.

          '
        in: query
        name: personalInfo
        required: false
        schema:
          type: boolean
          default: true
      - description: 'Expand associated records using one or more valid field names. A value of "all" will expand all expandable fields.

          '
        in: query
        name: expand
        schema:
          items:
            enum:
            - permissions
            - assignable
            - all
            type: string
          type: array
        style: form
      - name: fields
        in: query
        style: form
        description: Only return fields with these keys from the output. Use dot notation for nested fields.
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Role'
                type: array
          description: Success
      tags:
      - Roles
      summary: List roles.
      x-addon: dashboard
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
          description: Success
      tags:
      - Roles
      requestBody:
        $ref: '#/components/requestBodies/RolePost'
      summary: Add a role.
      x-addon: dashboard
  /roles/{id}:
    delete:
      parameters:
      - description: 'The role ID.

          '
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Success
      tags:
      - Roles
      summary: Delete a role.
      x-addon: dashboard
    get:
      parameters:
      - description: 'The role ID.

          '
        in: path
        name: id
        required: true
        schema:
          type: integer
      - description: 'Expand associated records using one or more valid field names. A value of "all" will expand all expandable fields.

          '
        in: query
        name: expand
        schema:
          items:
            enum:
            - permissions
            - all
            type: string
          type: array
        style: form
      - name: fields
        in: query
        style: form
        description: Only return fields with these keys from the output. Use dot notation for nested fields.
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
          description: Success
      tags:
      - Roles
      summary: Get a role.
      x-addon: dashboard
    patch:
      parameters:
      - description: The role ID.
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
          description: Success
      tags:
      - Roles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RolePost'
        required: true
      summary: Update a role.
      x-addon: dashboard
  /roles/{id}/edit:
    get:
      parameters:
      - description: 'The role ID.

          '
        in: path
        name: id
        required: true
        schema:
          type: integer
      - name: fields
        in: query
        style: form
        description: Only return fields with these keys from the output. Use dot notation for nested fields.
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  canSession:
                    description: Can users in this role start a session?
                    type: boolean
                  deletable:
                    description: Is the role deletable?
                    type: boolean
                  description:
                    description: Description of the role.
                    minLength: 0
                    nullable: true
                    type: string
                  name:
                    description: Name of the role.
                    minLength: 1
                    type: string
                  personalInfo:
                    description: Is membership in this role personal information?
                    type: boolean
                  roleID:
                    description: ID of the role.
                    type: integer
                  type:
                    description: Default type of this role.
                    minLength: 0
                    nullable: true
                    type: string
                  domains:
                    description: Email domains of roles.
                    minLength: 0
                    nullable: true
                    type: string
                required:
                - roleID
                - name
                - description
                - type
                - deletable
                - canSession
                - personalInfo
                type: object
          description: Success
      tags:
      - Roles
      summary: Get a role for editing.
      x-addon: dashboard
  /roles/{id}/permissions:
    patch:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PermissionFragment'
                type: array
          description: Success
      tags:
      - Roles
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/PermissionFragment'
              type: array
        required: true
      summary: Update permissions on a role
      x-addon: dashboard
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PermissionFragment'
                type: array
          description: Success
      tags:
      - Roles
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/PermissionFragment'
              type: array
        required: true
      summary: Overwrite all permissions for a role.
      x-addon: dashboard
components:
  requestBodies:
    RolePost:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolePost'
      required: true
      x-addon: dashboard
  schemas:
    PermissionFragment:
      properties:
        id:
          type: integer
        permissions:
          type: object
        type:
          enum:
          - global
          - category
          minLength: 1
          type: string
      required:
      - type
      - permissions
      type: object
      x-addon: dashboard
    Role:
      properties:
        canSession:
          description: Can users in this role start a session?
          type: boolean
        deletable:
          description: Is the role deletable?
          type: boolean
        description:
          description: Description of the role.
          minLength: 0
          nullable: true
          type: string
        name:
          description: Name of the role.
          minLength: 1
          type: string
        permissions:
          items:
            $ref: '#/components/schemas/PermissionFragment'
          type: array
        personalInfo:
          description: Is membership in this role personal information?
          type: boolean
        roleID:
          description: ID of the role.
          type: integer
        type:
          description: Default type of this role.
          minLength: 0
          nullable: true
          type: string
        domains:
          description: Email domains of roles.
          minLength: 0
          nullable: true
          type: string
      required:
      - roleID
      - name
      - description
      - type
      - deletable
      - canSession
      - personalInfo
      type: object
      x-addon: dashboard
    RolePost:
      properties:
        canSession:
          description: Can users in this role start a session?
          type: boolean
        deletable:
          description: Is the role deletable?
          type: boolean
        description:
          description: Description of the role.
          minLength: 0
          nullable: true
          type: string
        name:
          description: Name of the role.
          minLength: 1
          type: string
        permissions:
          items:
            $ref: '#/components/schemas/PermissionFragment'
          type: array
        personalInfo:
          description: Is membership in this role personal information?
          type: boolean
        type:
          description: Default type of this role.
          minLength: 0
          nullable: true
          type: string
        domains:
          description: Email domains of roles.
          minLength: 0
          nullable: true
          type: string
      required:
      - name
      type: object
      x-addon: dashboard
x-resourceEvents:
  emailTemplates:
    x-feature: Feature.emailTemplates.Enabled
    name: Email Template
    type: emailTemplate
  notification:
    x-addon: dashboard
    name: Notification
    type: notification
  reaction:
    name: Reaction
    type: reaction
  user:
    x-addon: dashboard
    name: User
    type: user
  comment:
    x-addon: vanilla
    name: Comment
    type: comment
  discussion:
    x-addon: vanilla
    name: Discussion
    type: discussion
  escalation:
    x-addon: vanilla
    name: Escalation
    type: cmdEscalation
  report:
    x-addon: vanilla
    name: Report
    type: report
  userNote:
    x-addon: warnings2
    name: User Note
    type: userNote
x-aliases:
  AssetOut:
    type:
      description: The type of the asset.
      type: string
    url:
      type: string
      description: Absolute URL of the asset.
    content-type:
      description: The content-type of the asset.
      type: string
      example: application/json
  StringAssetOut:
    type:
      description: The type of the asset.
      type: string
    url:
      type: string
      description: Absolute URL of the asset.
    content-type:
      description: The content-type of the asset.
      type: string
      example: application/json
    data:
      type: string
      description: Contents of the asset. May require an expand parameter to retreive.
    '200':
      content:
        application/json:
          schema:
            description: Contents of an asset.
            type: object
            properties:
              type:
                description: The type of the asset.
                type: string
                example: html
                enum:
                - html
                - css
                - js
              data:
                type: string
                example: <header>Hello Footer<footer />
                description: Contents of the asset. May require an expand parameter to retreive.
              content-type:
                description: The content-type of the asset.
                type: string
                example: text/html
              url:
                type: string
                description: Absolute URL of the resource.
                example: https://site.com/api/v2/themes/:themeID/assets/:assetName.ext?v=faasdf42d
      description: Success
  ThemeSlug:
    description: Unique theme slug.
    in: path
    name: themeID
    required: true
    schema:
      type: string
  AssetNotFound:
    description: JavaScript could not be found.
    content:
      application/json:
        schema:
          type: object
          properties:
            description:
              description: Verbose description of the error.
              nullable: true
              type: string
            message:
              description: Short description of the error.
              type: string
            status:
              description: Status code of the error response.
              type: integer
          required:
          - description
          - message
          - status
  ThemeIDParam:
    description: Unique themeID.
    in: path
    name: themeID
    required: true
    schema:
      type: integer
  StringAssetIn:
    description: An asset to be inserted.
    type: object
    properties:
      type:
        description: The type of the asset.
        type: string
        example: html
        enum:
        - html
        - css
        - js
      data:
        type: string
        example: <header>Hello Footer<footer />
        description: Contents of the asset. May require an expand parameter to retreive.
  JsonAssetIn:
    description: An asset to be inserted.
    type: object
    properties:
      type:
        type: string
        example: json
      data:
        type: object
        description: JSON content of the asset.
        example:
          global:
            mainColors:
              primary: '#5cc530'
  JsonAssetOut:
    '200':
      content:
        application/json:
          schema:
            type: object
            properties:
              type:
                type: string
                example: json
              data:
                type: object
                description: JSON content of the asset.
                example:
                  global:
                    mainColors:
                      primary: '#5cc530'
              content-type:
                description: The content-type of the asset.
                type: string
                example: application/json
              url:
                type: string
                description: Absolute URL of the resource.
                example: https://site.com/api/v2/themes/:themeID/assets/:assetName.ext?v=faasdf42d
      description: Success
  DeleteAsset:
    parameters:
    - description: Unique themeID.
      in: path
      name: themeID
      required: true
      schema:
        type: integer
    responses:
      '204':
        description: Success
    tags:
    - Theme Assets
    summary: Delete theme asset.
  StringPutAsset:
    parameters:
    - description: Unique themeID.
      in: path
      name: themeID
      required: true
      schema:
        type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            description: An asset to be inserted.
            type: object
            properties:
              type:
                description: The type of the asset.
                type: string
                example: html
                enum:
                - html
                - css
                - js
              data:
                type: string
                example: <header>Hello Footer<footer />
                description: Contents of the asset. May require an expand parameter to retreive.
    responses:
      '200':
        content:
          application/json:
            schema:
              description: Contents of an asset.
              type: object
              properties:
                type:
                  description: The type of the asset.
                  type: string
                  example: html
                  enum:
                  - html
                  - css
                  - js
                data:
                  type: string
                  example: <header>Hello Footer<footer />
                  description: Contents of the asset. May require an expand parameter to retreive.
                content-type:
                  description: The content-type of the asset.
                  type: string
                  example: text/html
                url:
                  type: string
                  description: Absolute URL of the resource.
                  example: https://site.com/api/v2/themes/:themeID/assets/:assetName.ext?v=faasdf42d
        description: Success
    tags:
    - Theme Assets
    summary: Set theme asset or replace if already exists.
  HtmlPutAssetContentType:
    parameters:
    - description: Unique themeID.
      in: path
      name: themeID
      required: true
      schema:
        type: integer
    requestBody:
      required: true
      content:
        text/html:
          schema:
            type: string
            description: HTML contents.
            example: <div>Hello HTML Asset!</div>
    responses:
      '200':
        content:
          text/html:
            schema:
              type: string
              description: HTML contents.
              example: <div>Hello HTML Asset!</div>
        description: Success
    tags:
    - Theme Assets
    summary: Set theme asset or replace if already exists.
  JsPutAssetContentType:
    parameters:
    - description: Unique themeID.
      in: path
      name: themeID
      required: true
      schema:
        type: integer
    requestBody:
      required: true
      content:
        application/javascript:
          schema:
            type: string
            description: HTML contents.
            example: console.log('Hello Javascript')
    responses:
      '200':
        content:
          application/javascript:
            schema:
              type: string
              description: HTML contents.
              example: console.log('Hello Javascript')
        description: Success
    tags:
    - Theme Assets
    summary: Set theme asset or replace if already exists.
  CssPutAssetContentType:
    parameters:
    - description: Unique themeID.
      in: path
      name: themeID
      required: true
      schema:
        type: integer
    requestBody:
      required: true
      content:
        text/css:
          schema:
            type: string
            description: HTML contents.
            example: ".class {\n   color: orange;\n}\n"
    responses:
      '200':
        content:
          text/css:
            schema:
              type: string
              description: HTML contents.
              example: ".class {\n   color: orange;\n}\n"
        description: Success
    tags:
    - Theme Assets
    summary: Set theme asset or replace if already exists.
  JsonPutAsset:
    parameters:
    - description: Unique themeID.
      in: path
      name: themeID
      required: true
      schema:
        type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            description: An asset to be inserted.
            type: object
            properties:
              type:
                type: string
                example: json
              data:
                type: object
                description: JSON content of the asset.
                example:
                  global:
                    mainColors:
                      primary: '#5cc530'
    responses:
      '200':
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: json
                data:
                  type: object
                  description: JSON content of the asset.
                  example:
                    global:
                      mainColors:
                        primary: '#5cc530'
                content-type:
                  description: The content-type of the asset.
                  type: string
                  example: application/json
                url:
                  type: string
                  description: Absolute URL of the resource.
                  example: https://site.com/api/v2/themes/:themeID/assets/:assetName.ext?v=faasdf42d
        description: Success
    tags:
    - Theme Assets
    summary: Set theme asset or replace if already exists.
  JsonPutAssetContentType:
    parameters:
    - description: Unique themeID.
      in: path
      name: themeID
      required: true
      schema:
        type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            description: JSON contents of the asset.
            example:
              hello:
                json:
                  asset: true
    responses:
      '200':
        content:
          application/json:
            schema:
              type: object
              description: JSON contents of the asset.
              example:
                hello:
                  json:
                    asset: true
        description: Success
    tags:
    - Theme Assets
    summary: Set theme asset or replace if already exists.
